environment:
  matrix:
  - nodejs_version: '15'

install:
  - ps: Install-Product node $env:nodejs_version
  - cd ./server
  - yarn install --ignore-engines

before_test:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb mediumclone
  - SET NODE_ENV=test

services:
  - postgresql101

test_script:
  - yarn test

build: off